############################################################
# This image is used for the test harness.
# It is not published anywhere.
#
# As of alpine:3.7, tftp client is in busybox-extras.
############################################################
FROM alpine:3.13.5
RUN apk add --no-cache busybox-extras
