---
version: '2.1'

networks:
  testnet:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.254.0/24
          gateway: 192.168.254.1

services:
  tftp-hpa:
    image: tftp-hpa
    build:
      context: src/
    volumes_from:
      - rsyslogd
    networks:
      testnet:
        ipv4_address: 192.168.254.253
    pids_limit: 10
    cpu_shares: 1023
    mem_limit: 100m
    shm_size: 32m
    stdin_open: true
    tty: true

  rsyslogd:
    image: jumanjiman/rsyslog
    networks:
      testnet:
        ipv4_address: 192.168.254.252
    cap_drop:
      - all
    cap_add:
      - net_bind_service
    pids_limit: 20
    cpu_shares: 1023
    mem_limit: 100m
    shm_size: 32m
    stdin_open: true
    tty: true

  tftp:
    image: client
    build:
      context: client/
    networks:
      testnet:

  version:
    image: tftp-hpa
    entrypoint:
      - sh
    command:
      - -c
      - "apk policy tftp-hpa 2>/dev/null | tail -n +2 | head -1 | tr -d ' :'"
