---
version: '2.1'

services:
  tagged: &tagged
    image: jumanjiman/tftp-hpa:${TAG}
    build:
      context: src/
      labels:
        - io.github.jumanjiman.name=jumanjiman/tftp-hpa
        - io.github.jumanjiman.description=H. Peter Anvin tftp server in a container with syslinux files
        - io.github.jumanjiman.url=https://github.com/jumanjihouse/docker-tftp-hpa
        - io.github.jumanjiman.license=MIT
        - io.github.jumanjiman.docker.dockerfile=/src/Dockerfile
        - io.github.jumanjiman.vcs-type=Git
        - io.github.jumanjiman.vcs-url=https://github.com/jumanjihouse/docker-tftp-hpa.git
        - io.github.jumanjiman.version=${VERSION}
        - io.github.jumanjiman.build-date=${BUILD_DATE}
        - io.github.jumanjiman.vcs-ref=${VCS_REF}
        - io.github.jumanjiman.ci-build-url=${CI_BUILD_URL}

  latest:
    <<: *tagged
    image: jumanjiman/tftp-hpa
