#!/bin/bash
set -e

. script/functions

echo
echo "===> Build a tiny tftp server image."
smitty docker build \
    --rm \
    --build-arg CI_BUILD_URL=${CIRCLE_BUILD_URL} \
    --build-arg BUILD_DATE=${BUILD_DATE} \
    --build-arg VCS_REF=${VCS_REF} \
    --build-arg VERSION=${VERSION} \
    --tag tftp-hpa \
    src/

echo
echo "===> Show image sizes."
docker images | egrep 'tftp-hpa\b'


echo
echo "WARN: you should docker tag the image"
echo
