#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Run "ci/bootstrap" to install dependencies for the test harness.
################################################################################

main() {
  setup_python_path
  install_precommit
}

trap finish EXIT

finish() {
  declare -ri RC=$?
  if [[ ${RC} -eq 0 ]]; then
    echo "$0 OK" >&2
  else
    echo "[ERROR] $0" >&2
  fi
}

setup_python_path() {
  python_path="$(python -c "import site; print(site.USER_BASE)")"
  readonly python_path

  if ! grep -q "${python_path}/bin" <(env | grep PATH); then
    export PATH="${PATH}:${python_path}/bin"
  fi
}

install_precommit() {
  if ! command -v pre-commit &>/dev/null; then
    # Install for just this user. Does not need root.
    pip install --user -Iv --compile --no-cache-dir pre-commit
  fi
}

main
