#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Run "ci/bootstrap" to install dependencies for the test harness.
################################################################################

. ci/functions.sh

main() {
  setup_python_path
  install_precommit
  add_upstream_git_remote
  fetch_upstream
}

setup_python_path() {
  python_path="$(python -c "import site; print(site.USER_BASE)")"
  readonly python_path

  if ! grep -q "${python_path}/bin" <(env | grep PATH); then
    export PATH="${PATH}:${python_path}/bin"
  fi
}

install_precommit() {
  # Install for just this user. Does not need root.
  run pip install \
    --compile \
    --disable-pip-version-check \
    --quiet \
    --user \
    --verbose \
    -r ci/requirements.txt

  run pre-commit install-hooks
}

add_upstream_git_remote() {
  if ! git remote show upstream &>/dev/null; then
    git remote add upstream https://github.com/jumanjihouse/docker-tftp-hpa.git
  fi
}

fetch_upstream() {
  git fetch upstream
}

main
