#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Build image(s). Invoke as "ci/build".
################################################################################

cat >ci/vars <<EOF
declare -rx APP_VERSION=6.04_pre1-r1
declare -rx BUILD_DATE=$(date +%Y%m%dT%H%M)
declare -rx VCS_REF=$(git rev-parse --short HEAD)
declare -rx TAG=\${APP_VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
declare -rx CI_BUILD_URL=${CIRCLE_BUILD_URL:-unknown}
EOF

. ci/vars
. ci/functions.sh

echo
echo "===> Build a tiny tftp server image."
smitty docker-compose build tftp-hpa

echo
echo "===> Show image sizes."
docker images | grep -E 'tftp-hpa\b'

echo
echo "WARN: you should docker tag the image"
echo
