#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Build image(s). Invoke as "ci/build".
################################################################################
. ci/functions.sh

info "Build a tiny tftp server image."
run docker-compose build tftp-hpa

info "Show image sizes."
docker images | grep -E 'tftp-hpa\b'

warn "Run ci/tag to tag the image."
