#!/bin/sh

. ci/vars
docker login -e ${mail} -u ${user} -p ${pass}
docker tag tftp-hpa jumanjiman/tftp-hpa:${TAG}
docker tag tftp-hpa jumanjiman/tftp-hpa:latest
docker push jumanjiman/tftp-hpa:${TAG}
docker push jumanjiman/tftp-hpa:latest
docker logout
curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/tftp-hpa/U2HFgtW4uaY4oUTMxuzljwV-kZU='
