#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Publish image(s). Invoke as "ci/publish".
################################################################################

. ci/vars
. ci/functions.sh

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"
run docker tag tftp-hpa jumanjiman/tftp-hpa:"${TAG}"
run docker tag tftp-hpa jumanjiman/tftp-hpa:latest
run docker push jumanjiman/tftp-hpa:"${TAG}"
run docker push jumanjiman/tftp-hpa:latest
docker logout
run curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/tftp-hpa/U2HFgtW4uaY4oUTMxuzljwV-kZU='
echo
