#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################

. ci/bootstrap
. ci/vars
. ci/functions.sh

info "Run various file checks."
run pre-commit run --all-files --verbose --hook-stage manual

info "Clean up from previous test runs."
rm -f /tmp/pxelinux.0
rm -f /tmp/default1
rm -f /tmp/default2
rm -f /tmp/F1.msg

info "Start a syslog server container."
run docker-compose up -d rsyslogd

info "Show tftp-hpa build options."
run docker run --rm -t tftp-hpa -V

info "Start server."
run docker-compose up -d tftp-hpa

info "Test that we can download files via tftp client."
info "... /pxelinux.cfg/default (fully-qualified)"
run docker-compose run --rm tftp tftp -gr /pxelinux.cfg/default 192.168.254.253
info "... \\pxelinux.cfg\\default (fully-qualified, backslashes)"
run docker-compose run --rm tftp tftp -gr \\pxelinux.cfg\\default 192.168.254.253
info "... pxelinux.0 (not fully-qualified)"
run docker-compose run --rm tftp tftp -gr pxelinux.0 192.168.254.253
info "... pxelinux.cfg/F1.msg (should be downcased by map file)"
run docker-compose run --rm tftp tftp -gr /pxelinux.cfg/F1.msg 192.168.254.253

info "Test that logs are meaningful."
run docker-compose logs rsyslogd | tee /tmp/logs.out
grep 'RRQ from 192.168.254.* filename pxelinux.0 remapped to' /tmp/logs.out

info "Shut down."
run docker-compose down
